account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import *
import information.views

app_name = "account"
urlpatterns = [
    path('login/', LoginView.as_view(template_name ='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name ='account/logout.html'), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('', information.views.main, name="main"),
]

artego/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import information.views
import information.forms
# import account.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', information.views.main, name="main"),
    path('event/', information.views.event, name="event"),
    path('calendar/', information.views.calendar, name="calendar"),
    path('info/', information.views.info, name="info"),
    path('info/<int:blog_id>', information.views.detail, name="detail"),
    path('info/comment/<int:blog_id>', information.views.add_comment, name="add_comment"),
    path('search/', information.views.search, name="search"),
    path('account/', include('account.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

information/urls.py
from django.contrib import admin
from django.urls import path, include
import information.views
import information.forms
# import account.views

urlpatterns = [
    path('search/', information.views.SearchFormView.as_view(), name='search'),
]

account/models.py
from django.db import models

# Create your models here.

information/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Information(models.Model):
    WISH=(
        ('V', 'visited'),
        ('W', 'wish'),
        ('N', 'not yet'),
    )
    title=models.CharField(max_length=200)
    image=models.ImageField(upload_to='images/', default="")
    info_data=models.TextField()
    wish=models.CharField(max_length=1, choices=WISH, default='N')
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    post=models.ForeignKey(Information, related_name='comments', on_delete=models.CASCADE)
    author_name=models.CharField(max_length=20)
    comment_text=models.TextField()
    time=models.DateTimeField(default=timezone.now)

    def approve(self):
        self.save()
    
    def __str__(self):
        return self.comment_text

information/forms.py
from django import forms
from .models import Comment


class SearchForm(forms.Form): 
    word = forms.CharField(label='Search Word')

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('author_name', 'comment_text')

account/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


class UserCreateView(CreateView):
    template_name = 'account/signup.html'
    form_class=UserCreationForm
    success_url=reverse_lazy('account:register_done')

class UserCreateDoneTV(TemplateView):
    template_name='account/register_done.html'

def main(request):
    return render(request, 'information/information.html')

information/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Information
from django.contrib import messages
from django.db.models import Q
from .forms import CommentForm
from .forms import SearchForm
from django.views.generic.edit import FormView

# Create your views here.

def main(request):
    return render(request, 'main.html')

def info(request):
    informations=Information.objects
    return render(request, 'information.html', {'informations':informations})

def event(request):
    return render(request, 'event.html')

def calendar(request):
    return render(request, 'mycalendar.html')

def search(request):
    information=Information.objects.all()
    query=None

    if 'q' in request.GET:
        query=request.GET.get('q')
        if query:
            information=information.filter(Q(title__icontains=query)|Q(info_data__icontains=query))
    return render(request, 'search.html', {'information' : information, 'query' : query})



def detail(request, blog_id):
    blog_object=get_object_or_404(Information, pk=blog_id)
    return render(request, 'detail.html', {'information':blog_object})

def add_comment(request, blog_id):
    blog=get_object_or_404(Information, pk=blog_id)
    
    if request.method == "POST":
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=blog
            comment.save()
            return redirect('detail', blog_id)
    else:
        form=CommentForm()
        return render(request, 'review.html', {'form':form})

information/templates/detail.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>ArtEgo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Song+Myung&display=swap" rel="stylesheet">

  <style>
    body{background-color: #DAD9D9;color: #365264;font-family: "Song Myung";}
    header{text-align:center;font-size:50px;font-family:"Lobster", bold;padding:20px;}
    nav{padding:5px;overflow:hidden;text-align:right;}
    nav a{font-size:15px;display:block;color:#365264;text-decoration:none;}
    nav li{list-style:none;display:inline-block;padding:5px;}
    h2{font-family: "Song Myung"; font-size: 36px; font-weight: lighter;}
    .wrapper{width: 1000px;margin: 20px auto;text-align: left;border:none;}
    .button{color: #365264;background-color:#DAD9D9;border:0;outline:0;cursor: pointer;}

    #info-container:: after{content: "";clear: both;display: table;}
    .column{float:left; width:45%; height: 400px;margin: 10px; font-size: 20px;}
    .column img{float: right; height: 100%;}

    #info{padding: 10px;}
    #ttl{font-weight:bold;font-size: 30px;}
    #more{color: #44677E;}

    table{
      border-collapse:separate;
      border-spacing:20px 0px;
    }
    a:link{text-decoration : none; color:black;}
      a:visited{color:black;}
  </style>
</head>
</head>
<body>
  <div class = "wrapper" id = "reviewPage">
    <!--fixed UI until **---------------------------------------------->
    <section id = "menu-container">
        <nav>
          <ul>
            <li><a href="{%url 'info' %}"><i class="fa fa-fw fa-home"></i>HOME</a></li>
            <li><a href="{% url 'event' %}"><i class="fa fa-fw fa-star"></i>EVENT</a></li>
            <li><a href="{% url 'calendar' %}"><i class="fa fa-fw fa-calendar"></i>MY CALENDAR</a></li>
            <li><a href="{% url 'account:logout' %}"><i class="fa fa-fw fa-user"></i>LOG OUT</a></li>
          </ul>
        </nav>
        <!--Logo-->
        <header>ArtEgo</header>
      </section>
      <!-- ** -------------------------------------------------------->
      <!--title goes here-->

          

<div>
  <table>
  <caption><h1 >information</h1></caption>
  <td>
    <img src ="{{information.image.url}}" width=500px height=auto>
  </td>
  <td><label id = "ttl">{{information.title}}</label>
    <div id = "information">
      <p style="font-size:20px">{{information.info_data|linebreaksbr}}</p>

    </div>  
  </td>
</table>
</div>

<div>
    {% for comment in information.comments.all %}
        <h3>{{comment.author_name}}</h3>
        <p>{{comment.time}}</p>
        <p>{{comment.comment_text}}</p>
    {% empty %}
    <p>No comments here yet</p>
    {% endfor %}

    <br>
    <a href="{% url 'add_comment' information.id %}"><p style="font-size:30px"> new comment</p></a>

</div>
        </div>
      </section>
  </div>
</body>
</html>

information/templates/event.html
<!-- event page-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
      <title>ArtEgo</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Song+Myung&display=swap" rel="stylesheet">
      <style>
       body{background-color: #DAD9D9;color: #365264;font-family: "Song Myung";}
        header{text-align:center;font-size:50px;font-family:"Lobster", bold;padding:20px;}
        nav{padding:5px;overflow:hidden;text-align:right;}
        nav a{font-size:15px;display:block;color:#365264;text-decoration:none;}
        nav li{list-style:none;display:inline-block;padding:5px;}
        h1{font-family: "Song Myung"; font-size: 36px; font-weight: lighter;}
        h2{font-family: "Song Myung"; font-size: 36px; font-weight: lighter;}
        p{font-size:20px;}
    
        .wrapper{width: 1000px;margin: 20px auto;text-align: left;border:none;}
        .button{color: #365264;background-color:#DAD9D9;border:0;outline:0;cursor: pointer; font-family: "Song Myung";}
    
      #event-container{padding:30px;}
      .poster-container {background-color:black;position: relative; width: 400px;height:600px;}
      .dot-container{text-align:center; width:400px};
      .poster {display: none;}
      .poster img{max-width:100%; max-height:100%;}
      .prev, .next {cursor: pointer;position: absolute;top: 50%;width: auto;padding: 16px;
        margin-top: -22px;color: white;font-weight: bold;font-size: 18px;transition: 0.6s ease;
        border-radius: 0 3px 3px 0;user-select: none;}
      .next {right: 0;border-radius: 3px 0 0 3px;}
      .prev:hover, .next:hover {background-color: rgba(0,0,0,0.8);}
      .text {color: #f2f2f2;font-size: 15px;padding: 8px 12px;position: absolute;bottom: 8px;width: 100%;text-align: center;}
      .numbertext {color: #f2f2f2;padding: 8px 12px;position: absolute;top: 0;}
      .dot {cursor: pointer;height: 15px;width: 15px;margin: 0 2px;background-color: #bbb;
        border-radius: 50%;display: inline-block;transition: background-color 0.6s ease;}
      .active, .dot:hover {background-color: #717171;}
      .fade {
        -webkit-animation-name: fade;
        -webkit-animation-duration: 1.5s;
        animation-name: fade;
        animation-duration: 1.5s;
      }

      .goods-container {position:relative; width: 1000px;}

      @-webkit-keyframes fade {
        from {opacity: .4}
        to {opacity: 1}
      }
      @keyframes fade {
        from {opacity: .4}
        to {opacity: 1}
      }
      @media only screen and (max-width: 300px) {
        .prev, .next,.text {font-size: 11px}
      }
    </style>
  </head>
  <body>
    <section id="logged-out-main-container">
      <header style="font-family:Lobster; font-size:80px;">ArtEgo</header>
    </section>
    <!--fixed UI until **---------------------------------------------->
    <div class = "wrapper" id = "eventPage">
      <section id = "menu-container">
        <nav>
          <ul>
            <li><a href="{%url 'info' %}"><i class="fa fa-fw fa-home"></i>HOME</a></li>
            <li><a href="{% url 'event' %}"><i class="fa fa-fw fa-star"></i>EVENT</a></li>
            <li><a href="{% url 'calendar' %}"><i class="fa fa-fw fa-calendar"></i>MY CALENDAR</a></li>
            <li><a href="{% url 'account:logout' %}"><i class="fa fa-fw fa-user"></i>LOG OUT</a></li>
          </ul>
        </nav>
        <!--Logo-->
       
      </section>
      <!-- ** -------------------------------------------------------->
      <section id = "event-container">
        <h2>EVENTS</h2>

        <div class="poster-container">
          <div class="poster fade">
            <div class="numbertext">1 / 3</div>

              <img src = "http://spacelifes.com/wp-content/uploads/2017/09/2.jpg">

            <div class="text" >Discount 30%</div>
          </div>
          <div class="poster fade">
            <div class="numbertext">2 / 3</div>

              <img src= "http://58.234.158.21:8081/Upload/Image/20170217/00000000000000016304.jpg" >

            <div class="text" >Free</div>
          </div>
          <div class="poster fade">

            <div class="numbertext">3 / 3</div>
            <img src= "http://www.art114.kr/files/attach/images/1337/112/598/1cda2cc1b363963a6909cbed521df07d.jpg">
            <div class="text" href = "review.html">Opening Event</div>

          </div>
          <a class="prev" onclick="plusSlides(-1)"><i class = "fa fa-fw fa-arrow-left"></i></a>
          <a class="next" onclick="plusSlides(1)"><i class = "fa fa-fw fa-arrow-right"></i></a>
        </div>
        <br>
        <div class = "dot-container">
          <span class="dot" onclick="currentSlide(1)"></span>
          <span class="dot" onclick="currentSlide(2)"></span>
          <span class="dot" onclick="currentSlide(3)"></span>
        </div>
        <h2>GOODS</h2>
        <div class = "goods-container"></div>
      </section>
              </div>

      <script>
      var slideIndex = 1;
      showSlides(slideIndex);

      function plusSlides(n) {
        showSlides(slideIndex += n);
      }

      function currentSlide(n) {
        showSlides(slideIndex = n);
      }

      function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("poster");
        var dots = document.getElementsByClassName("dot");
        if (n > slides.length) {slideIndex = 1}
        if (n < 1) {slideIndex = slides.length}
        for (i = 0; i < slides.length; i++) {
          slides[i].style.display = "none";
        }
        for (i = 0; i < dots.length; i++) {
          dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex-1].style.display = "block";
        dots[slideIndex-1].className += " active";
        }
    </script>

  </body>
</html>

information/templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">

  <title>ArtEgo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Song+Myung&display=swap" rel="stylesheet">
  <style>
    body{background-color: #DAD9D9;color: #365264;font-family: "Song Myung";}
    header{text-align:center;font-size:50px;font-family:"Lobster", bold;padding:20px;}
    nav{padding:5px;overflow:hidden;text-align:right;}
    nav a{font-size:15px;display:block;color:#365264;text-decoration:none;}
    nav li{list-style:none;display:inline-block;padding:5px;}
    h2{font-family: "Song Myung"; font-size: 36px; font-weight: lighter;}

    .wrapper{width: 1000px;margin: 20px auto;text-align: left;border:none;}
    .button{color: #365264;background-color:#DAD9D9;border:0;outline:0;cursor: pointer; font-family: "Song Myung";}

    #log-out-container{text-align:center; font-size: 20px;}

    a:link {
      text-decoration: none
    }

    a:visited {
      color: #365264;
    }
   
    /*intro-container*/
    #enter-container {
      position: relative;
      margin: 10px;
      text-align: center;
    }

    #frontPage {
      text-align: center;
    }

    #intro-container {
      position: relative;
      margin-left: 20%;
      margin-right: 20%;
    }

    /*poster*/
    .poster0 {
      position: relative;
      width: 100%;
    }

    .image0 {
      position: relative;
      top: 0;
      left: 0;
      max-width: 100%;
    }

    .overlay0 {
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      height: 100%;
      width: 100%;
      opacity: 0;
      transition: .5s ease;
      background-color: rgba(194, 203, 208, 0.5)
    }

    .poster0:hover .overlay0 {
      opacity: 1;
    }

    .text {
      color: white;
      font-size: 30px;
      position: absolute;
      top: 50%;
      left: 50%;
      text-decoration: none;
      -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
    }

      /*search*/
    .button{color: #365264;background-color:#DAD9D9;border:0;outline:0;cursor: pointer;}
    #search-engine{text-align:center;}
    #search-engine input{font-family: Verdana;text-align:left;width:40%;height: 25px;
      border: 2px solid #365264;outline:0;}
    #search-engine button{font-size:20px;}
    #region-search {text-align:right;}
    #region-search button{font-family:Verdana, bold;font-size:15px; padding-bottom:5px;}
    .map {display: none;position: fixed;z-index: 1;padding-top: 100px;left: 0;top: 0;
      width: 100%;height: 100%;overflow: auto;background-color: rgba(0,0,0,0.4);}
    .map-container {background-color: #edf0f1;margin: auto;padding: 20px;border: 1px solid #888;
      width: 60%; height: 80%;}
    .close {color: #365264;float: right;font-size: 28px;font-weight: bold;padding: 10px;}
    .close:hover,
    .close:focus {color: #000;text-decoration: none;cursor: pointer;}

    /*poster-list*/
    #image1{clip:rect(0px, 1000px, 400px, 0px);}
    #image2{clip:rect(400px, 1000px, 800px, 0px);}
    #image3{clip:rect(800px, 1000px, 1200px, 0px);}
    #overlay2 {top:400px;}
    #overlay3{top:800px;}
    .poster{position: absolute; width: 1000px;}
    .image{position:absolute;width:1000px;}
    .overlay {position: absolute; top: 0; bottom: 0; left: 0; right: 0;height: 400px; width: 1000px;
      opacity: 0; transition: .5s ease; background-color: rgba(194, 203, 208,0.5)}
    .poster:hover .overlay {opacity: 1;}
    .text {color: white;font-size: 30px;position: absolute;top: 50%;left: 50%;text-decoration: none;
      -webkit-transform: translate(-50%, -50%);-ms-transform: translate(-50%, -50%);
      transform: translate(-50%, -50%);text-align: right;}

      #view-more-container{display:block; border:1px solid;}
  </style>
</head>

<body>
  <div class="wrapper" id="frontPage">
    <!--fixed UI until **---------------------------------------->
    <section id="logged-out-main-container">
      <section id="logged-out-main-container">
        <header style="font-family:Lobster; font-size:80px;">ArtEgo</header>
      </section>
  
    {%if user.is_authenticated %}
    <section id = "logged-out-main-container">
    </section>

    <div class="wrapper" id="mainPage">
      <!--fixed UI until **---------------------------------------------->
      <section id="menu-container">
        <nav>
          <ul>
            <li><a href="{%url 'info' %}"><i class="fa fa-fw fa-home"></i>HOME</a></li>
            <li><a href="{% url 'event' %}"><i class="fa fa-fw fa-star"></i>EVENT</a></li>
            <li><a href="{% url 'calendar' %}"><i class="fa fa-fw fa-calendar"></i>MY CALENDAR</a></li>
            <li><a href="{% url 'account:logout' %}"><i class="fa fa-fw fa-user"></i>LOG OUT</a></li>
          </ul>
        </nav>
        <!--Logo-->
      </section>
      <!-- ** -------------------------------------------------------->

      <section id="logged-in-main-container">
        <div id="search-engine">
          <br><br>
            <div>
              <form method="GET" action="{% url 'search' %}">
                  {% csrf_token %}
                  <input type="search" name="q" value="{{q}}">
                  <button type="submit">Search</button>
              </form>
        </div>
        
        </div>
        <div id="region-search">

          <!--onclick => map UI-->
          <button id="mapButton" class="button">BY REGION</button>
          <div id="showMap" class="map">
            <div class="map-container">
              <div class="close">&times;</div>
              <div id="googleMap" style="width:100%;height:400px;"></div>
            </div>
          </div>
        </div>
      </section>
      <!--list of posters of the exhibitions-->

      <section id="exhibition-list-container">

        <div id="poster1" class="poster">
          <img src="http://spacelifes.com/wp-content/uploads/2017/09/2.jpg" id="image1" class="image">
          <div id="overlay1" class="overlay">
            <a class="text" href="{% url 'info' %}">Best of 2020<br>10th Dec, 2020<br>Seoul</a>
          </div>
        </div>
        <div id="poster2" class="poster">
          <img src="http://58.234.158.21:8081/Upload/Image/20170217/00000000000000016304.jpg" id="image2" class="image">
          <div id="overlay2" class="overlay">
            <a class="text">Best of 2020<br>10th Dec, 2020<br>Seoul</a>
          </div>
        </div>
        <div id="poster3" class="poster">
          <img src="http://www.art114.kr/files/attach/images/1337/112/598/1cda2cc1b363963a6909cbed521df07d.jpg"
            id="image3" class="image">
          <div id="overlay3" class="overlay">
            <a class="text">Best of 2020<br>10th Dec, 2020<br>Seoul</a>
          </div>
        </div>
      </section>

      <!-- for more information -->
      <section id="view-more-container">
        <button id="more">VIEW MORE</button>
      </section>
    </div>
    <div>
        {% for information in informations.all %}
         <div>
            <h1><a href="{% url 'detail' information.id %}">{{information.title}}</a></h1>
            <!-- <h1>{{information.wish}}</h1> -->
        </div>
        {% endfor %}
    </div>

    <script>
      var modal = document.getElementById("showMap");
      var btn = document.getElementById("mapButton");
      var span = document.getElementsByClassName("close")[0];

      //map-container
      btn.onclick = function () {
        modal.style.display = "block";
      }
      span.onclick = function () {
        modal.style.display = "none";
      }
      window.onclick = function (event) {
        if (event.target == modal) {
          modal.style.display = "none";
        }
      }

      //google-map
      function myMap() {
        var mapProp = {
          center: new google.maps.LatLng(51.508742, -0.120850),
          zoom: 5,
        };
        var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
      }
      //add marker
      var marker = new google.maps.Marker({
        position: myCenter
      });
      marker.setMap(map);

      var infowindow = new google.maps.InfoWindow({
        content: ""
      });
      google.maps.event.addListener(marker, 'click', function () {
        infowindow.open(map, marker);
      });

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY&callback=myMap"></script>

    {% else %}

    <!-- **----------------------------------------------->
    <!--intro page-->
      <h2>Exhibition of This Month</h2>
    <section id="intro-container">
      <div class="poster0">
        <!--poster-->
        <img
          src="http://kor.theasian.asia/wp-content/uploads/2020/11/200929_%EB%A7%88%ED%8B%B0%EC%8A%A4%ED%8F%AC%EC%8A%A4%ED%84%B0RGB-620x882.jpg"
          class="image0">
        <div class="overlay0">
          <a class="text" href="{% url 'info' %}">Best of 2020<br>10th Dec, 2020<br>Seoul</a>
        </div>
      </div>
    </section>
    <section id="enter-container">
      <a href="{% url 'account:login' %}"><button id="logIn" class="button" style="font-size: 20px;">LOG IN</button></a>
      <a href="{% url 'account:register' %}"><button id="join" class="button" style="font-size: 20px;">JOIN</button></a>
    </section>
  </div>
  {% endif %}
</body>

</html>

information/templates/review.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Song+Myung&display=swap" rel="stylesheet">

    <style>
    body{background-color: #DAD9D9;color: #365264;font-family: "Song Myung";}
    header{text-align:center;font-size:50px;font-family:"Lobster", bold;padding:20px;}
    nav{padding:5px;overflow:hidden;text-align:right;}
    nav a{font-size:15px;display:block;color:#365264;text-decoration:none;}
    nav li{list-style:none;display:inline-block;padding:5px;}
    h2{font-family: "Song Myung"; font-size: 36px; font-weight: lighter;}
    .wrapper{width: 1000px;margin: 20px auto;text-align: left;border:none;}

    /*intro-container*/
    #enter-container {
      position: relative;
      margin: 10px;
      text-align: center;
    }

    #frontPage {
      text-align: center;
    }

    #intro-container {
      position: relative;
      margin-left: 20%;
      margin-right: 20%;
    }

    /*poster*/
    .poster0 {
      position: relative;
      width: 100%;
    }

    .image0 {
      position: relative;
      top: 0;
      left: 0;
      max-width: 100%;
    }

    .overlay0 {
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      height: 100%;
      width: 100%;
      opacity: 0;
      transition: .5s ease;
      background-color: rgba(194, 203, 208, 0.5)
    }

    .poster0:hover .overlay0 {
      opacity: 1;
    }

    .text {
      color: white;
      font-size: 30px;
      position: absolute;
      top: 50%;
      left: 50%;
      text-decoration: none;
      -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
    }

    

    /*search*/
    .button{color: #365264;background-color:#DAD9D9;border:0;outline:0;cursor: pointer;}
    #search-engine{text-align:center;}
    #search-engine input{font-family: Verdana;text-align:left;width:40%;height: 25px;
      border: 2px solid #365264;outline:0;}
    #search-engine button{font-size:20px;}
    #region-search {text-align:right;}
    #region-search button{font-family:Verdana, bold;font-size:15px; padding-bottom:5px;}
    .map {display: none;position: fixed;z-index: 1;padding-top: 100px;left: 0;top: 0;
      width: 100%;height: 100%;overflow: auto;background-color: rgba(0,0,0,0.4);}
    .map-container {background-color: #edf0f1;margin: auto;padding: 20px;border: 1px solid #888;
      width: 60%; height: 80%;}
    .close {color: #365264;float: right;font-size: 28px;font-weight: bold;padding: 10px;}
    .close:hover,
    .close:focus {color: #000;text-decoration: none;cursor: pointer;}

    /*poster-list*/
    #image1{
      clip:rect(0px, 1000px, 400px, 0px);}
    #image2{clip:rect(400px, 1000px, 800px, 0px);}
    #image3{clip:rect(800px, 1000px, 1200px, 0px);}
    #overlay2 {top:400px;}
    #overlay3{top:800px;}
    .poster{position: absolute; width: 1000px;}
    .image{position:absolute;width:1000px;}
    .overlay {position: absolute; top: 0; bottom: 0; left: 0; right: 0;height: 400px; width: 1000px;
      opacity: 0; transition: .5s ease; background-color: rgba(194, 203, 208,0.5)}
    .poster:hover .overlay {opacity: 1;}
    .text {color: white;font-size: 30px;position: absolute;top: 50%;left: 50%;text-decoration: none;
      -webkit-transform: translate(-50%, -50%);-ms-transform: translate(-50%, -50%);
      transform: translate(-50%, -50%);text-align: right;}

      #view-more-container{display:block; border:1px solid;}

    .reposter{
      position:relative;
    }
    .posterimage{
      width:1000px;
      height:400px;
      clip:rect(0px, 1000px, 400px, 0px);
    }
    .postertext{
      position:absolute;
      text-align: center;
      top:50%;
      left:50%;
      transform: trnaslate(-50%, -50%);
    }

      a:link{text-decoration : none}
      a:visited{color:black;}
    .review{
      text-align: center;
    }
  </style>
</head>
<body>
  <section id="logged-out-main-container">
    <header style="font-family:Lobster; font-size:80px;">ArtEgo</header>
  </section>
  <div class="review">
    <h2>Review</h2>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Send</button>
    </form>
  </div>
</body>
</html>